<a href="https://colab.research.google.com/github/khushidubeyokok/PyTorch/blob/main/FundamentalsOfPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch**

import important libraries


In [127]:
import torch
import pandas as pd
import numpy as np
import matplotlib as md
print(torch.__version__)

2.4.0+cu121


## Creating Tensors


**Scalar** **Tensors**

In [5]:
Scalar_Tensor = torch.tensor(7)
Scalar_Tensor , Scalar_Tensor.dtype

(tensor(7), torch.int64)

In [3]:
Scalar_Tensor.ndim ##returns dimensions

0

In [4]:
 Scalar_Tensor.item() ##Returns the value of this tensor as a standard Python number.

7

**Vectors**

In [7]:
vector=torch.tensor([7,7])
vector , vector.dtype

(tensor([7, 7]), torch.int64)

In [8]:
vector.ndim ##number of dimensions

1

In [11]:
vector.shape ,  vector.size() ##returns size of the tensor

(torch.Size([2]), torch.Size([2]))

In [12]:
vector[0] ##returns element at index 0

tensor(7)

In [128]:
# vector.item() # error cannot be converted to scalar

**MATRICES**

In [14]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX , MATRIX.dtype

(tensor([[ 7,  8],
         [ 9, 10]]),
 torch.int64)

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape ##it has two rows and two columns

torch.Size([2, 2])

In [17]:
MATRIX[0]

tensor([7, 8])

**TENSORS**

In [18]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR , TENSOR.dtype

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 torch.int64)

In [20]:
  TENSOR.ndim

3

In [21]:
TENSOR.shape ##dim0=1, dim1=3, dim2=3

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [31]:
TENSOR2 = torch.tensor([[  [1,2,3],[3,6,9],[2,4,5]] , [[1,2,3],[3,6,8],[2,4,6]  ]])
TENSOR2 , TENSOR2.dtype

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],
 
         [[1, 2, 3],
          [3, 6, 8],
          [2, 4, 6]]]),
 torch.int64)

In [32]:
TENSOR2.ndim

3

In [33]:
TENSOR2.shape ##dim0=2, dim1=3, dim2=3

torch.Size([2, 3, 3])

In [34]:
TENSOR2[1]

tensor([[1, 2, 3],
        [3, 6, 8],
        [2, 4, 6]])

## CREATING RANDOM TENSORS

In [ ]:
RandomTensor = torch.rand(3,4)
RandomTensor , RandomTensor.dtype

(tensor([[0.4396, 0.9576, 0.4284, 0.7377],
         [0.5174, 0.9436, 0.7971, 0.4120],
         [0.5236, 0.7383, 0.4095, 0.2511]]),
 torch.float32)

In [ ]:
RandomTensor.ndim

2

**ZEROES** **TENSOR**

In [ ]:
zeroTensor=torch.zeros(size=(3,4,5))
zeroTensor


tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

**ONES** **TENSOR**

In [ ]:
OnesTensor=torch.ones(5,2,2)
OnesTensor

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

## Range of tensors and like tensors

In [41]:
RangeTensor=torch.arange(0,10,2) ##start,end,step
RangeTensor

tensor([0, 2, 4, 6, 8])

In [42]:
AlikeTensor=torch.zeros_like(input=RangeTensor)
AlikeTensor

tensor([0, 0, 0, 0, 0])

##Getting information from tensors

In [44]:
a=torch.tensor([5.,6.5])
b=a.type(torch.float16)
a.dtype, b.dtype , a.device

(torch.float32, torch.float16, device(type='cpu'))

In [45]:
a=torch.tensor([5.2,6.5])
print(a)
print(f"Datatype of tensor : {a.dtype}")
print(f"Shape of tensor : {a.shape}")
print(f"Device tensor is on : {a.device}")


tensor([5.2000, 6.5000])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([2])
Device tensor is on : cpu


## TENSOR OPERATIONS

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [46]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [47]:
tensor-10

tensor([-9, -8, -7])

In [48]:
tensor*10

tensor([10, 20, 30])

In [49]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [51]:
##Built-in function

print(f"Add : {torch.add(tensor,10)}")
print(f"Sub : {torch.sub(tensor,10)}")
print(f"Mul : {torch.mul(tensor,10)}")
print(f"Div : {torch.div(tensor,10)}")


Add : tensor([11, 12, 13])
Sub : tensor([-9, -8, -7])
Mul : tensor([10, 20, 30])
Div : tensor([0.1000, 0.2000, 0.3000])


**MATRIX MULTIPLICATION**

In [58]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[4,5,6],[7,8,9]])
c=b.T ##transpose

a @ c , torch.matmul(a,c) , torch.mm(a,c)

(tensor([[ 32,  50],
         [ 77, 122]]),
 tensor([[ 32,  50],
         [ 77, 122]]),
 tensor([[ 32,  50],
         [ 77, 122]]))

In [59]:
vector=torch.tensor([2,3,4])
vector2=torch.tensor([2,3,4])
vector.dot(vector2) ##dot product of oneD tensors

tensor(29)

## FINDING MIN,MAX,MEAN,SUM


In [63]:
x=torch.tensor([2,3,5])
print(f"Min : {x.min()} , {torch.min(x)}")
print(f"Max : {x.max()} , {torch.max(x)}")
## print(f"Mean : {x.mean()} , {torch.mean(x)}") , this will throw an error since x is of longint datatype
print(f"Mean : {x.type(torch.float32).mean()} , {torch.mean(x.type(torch.float32))}")  ## mean function requires a float32 tensor to work
print(f"Sum : {x.sum()} , {torch.sum(x)}")

Min : 2 , 2
Max : 5 , 5
Mean : 3.3333332538604736 , 3.3333332538604736
Sum : 10 , 10


In [64]:
print(f"Argmin : {x.argmin()} , {torch.argmin(x)}")
print(f"Argmax : {x.argmax()} , {torch.argmax(x)}")

Argmin : 0 , 0
Argmax : 2 , 2


##Reshaping , stacking, squeezing , unsqueezing TENSORS
- Reshape : Reshapes  input tensor to shape (if compatible)
- View : Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
- Stack : Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
- Squeeze : Squeezes  input tensor to remove all the dimenions with value 1
- Unsqueeze : Returns input tensor with a dimension value of 1 added at dim
- Permute : Returns a view of the original input with its dimensions permuted (rearranged) to dims.


In [74]:
a = torch.rand(3,4)
a.reshape(6,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])

In [68]:
b= a.view(6,2)
b

tensor([[0.5876, 0.0956],
        [0.4370, 0.0181],
        [0.8670, 0.8392],
        [0.2833, 0.4670],
        [0.8740, 0.1161],
        [0.0012, 0.8259]])

In [76]:
y=torch.stack([x,x,x],dim=0)
y

tensor([[2, 3, 5],
        [2, 3, 5],
        [2, 3, 5]])

In [80]:
M=torch.rand(2,2,1,2,1)
M

tensor([[[[[0.7539],
           [0.1952]]],


         [[[0.0050],
           [0.3068]]]],



        [[[[0.1165],
           [0.9103]]],


         [[[0.6440],
           [0.7071]]]]])

In [81]:
print(f"Shape : {M.shape}")
print(f"Squeezed : {M.squeeze().shape}")

Shape : torch.Size([2, 2, 1, 2, 1])
Squeezed : torch.Size([2, 2, 2])


In [83]:
print(f"Shape : {M.shape}")
print(f"Unsqueezed : {M.unsqueeze(dim=0).shape}")

Shape : torch.Size([2, 2, 1, 2, 1])
Unsqueezed : torch.Size([1, 2, 2, 1, 2, 1])


In [85]:
a.shape, a.permute(1,0).shape

(torch.Size([3, 4]), torch.Size([4, 3]))

INDEXING AND CHANGING VALUES

In [88]:
M[0],M[0,1,0]

(tensor([[[[0.7539],
           [0.1952]]],
 
 
         [[[0.0050],
           [0.3068]]]]),
 tensor([[0.0050],
         [0.3068]]))

In [95]:
# use ":" to select all of target dimension
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
A[:,2], A[0:3,1]

(tensor([3, 6, 9]), tensor([2, 5, 8]))

In [96]:
a=torch.tensor([[6,5],[6,5]])
a[1,0]=5
a

tensor([[6, 5],
        [5, 5]])

## Numpy and PyTorch
- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [106]:
NumpyArray=np.arange(1.0,8.0)
ArrayToTensor=torch.from_numpy(NumpyArray)
NumpyArray, ArrayToTensor  ##NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [107]:
TensorToArray=torch.Tensor.numpy(ArrayToTensor)
TensorToArray

array([1., 2., 3., 4., 5., 6., 7.])

In [108]:
ArrayToTensor=ArrayToTensor+1
ArrayToTensor, NumpyArray ##intial array remains the same

(tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

## REPRODUCIBILITY

In [109]:
RandomTensorA=torch.rand(3,4)
RandomTensorB=torch.rand(3,4)
print(f"Tensor A : {RandomTensorA}")
print(f"Tensor B : {RandomTensorB}")

Tensor A : tensor([[0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036]])
Tensor B : tensor([[0.2018, 0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155]])


TAKE OUT RANDOMNESS

In [110]:
torch.manual_seed(42)
RandomTensorC=torch.rand(3,4)
torch.manual_seed(42)
RandomTensorD=torch.rand(3,4)
print(f"Tensor C : {RandomTensorC}")
print(f"Tensor D : {RandomTensorD}")

Tensor C : tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D : tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


## GPUs and Pytorch

In [113]:
!nvidia-smi ## gives gpu details on colab
torch.cuda.is_available()

/bin/bash: line 1: nvidia-smi: command not found


False

In [114]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [115]:
# Count number of devices
torch.cuda.device_count()

0

In [119]:
# Create tensor (default on CPU)
a = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(a, a.device)

# Move tensor to GPU (if available)
tensor_on_gpu = a.to(device)
tensor_on_gpu,tensor_on_gpu.device

tensor([1, 2, 3]) cpu


(tensor([1, 2, 3]), device(type='cpu'))

In [125]:
# numpy works on cpu
# tensor_on_gpu.numpy() ##error
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)
print(tensor_on_gpu) # it remains the same on gpu

[1 2 3]
tensor([1, 2, 3])
